### ISSUE TITLE
Determine tasks for SSI-to-OIDC bridge release in SIWT

### ISSUE THREAD

**Issue by royscheeren** [ASCS-eV/envited-x-data-space#51]
# Problem statement
Felix has created a POC for a OIDC bridge. A version of this bridge will need to be released under SIWT. 
We need to understand exactly what needs to be done and what defines the definition of done.

# Todos

- [ ] Setup Felix's bridge
- [ ] Find out what missing/needs change etc
- [ ] Find out how it can be integrated into SIWT

# Definition of done
Clear path forward.
We have tasks.

Depends on #49 and #50
